### ISSUE TITLE
Sometimes need to call twice for correct result

### ISSUE THREAD

**Issue by dmittiga** [mfkasim91/unwrap_phase#1]
Thanks so much for creating this file, it is highly useful to me!

In the attached sample dataset (61x81), the unwrap_phase function must be called twice in order to get the correct output: unwrap_phase(unwrap_phase(phase))

Is this a flaw in the algorithm or in the implementation?

[phaseSample.zip](https://github.com/mfkasim91/unwrap_phase/files/3433396/phaseSample.zip)

**Comment by mfkasim1** [comment]
I think this is due to my implementation because I tried it on scikit-image's unwrap_phase and it seems fine.
But I don't know which part in the code might cause this.

**Comment by Leostar2054** [comment]
Hi, I tried this algorithm but it worked well with simulation but when I tried real images then results were not satisfactory, still there were some parts that did not unwrapped. Moreover, **performance gets worst with noisy images**. Any idea? what could be the problem? I am attaching images here too.

![with Noise](https://user-images.githubusercontent.com/64607461/128316947-719e8502-6a62-46d7-9ea2-36ca9ac37ac7.jpg)
![without noise](https://user-images.githubusercontent.com/64607461/128316965-68a331a6-6e9f-4e2e-9db0-e3d28b4a52d4.jpg)

**Comment by cweickhmann** [comment]
Hi @Leostar2054! Not sure if I read your images correctly: could you comment on the scale of the colourbar in the left vs. the right column?

**Comment by Leostar2054** [comment]
Hi, @cweickhmann colorbar is the value of phase, in Wrapped Phase, figure domain is [-pi, pi] but after unwrapping phase value is changed but it is not smooth still there is non-linear part and boundaries are already visible. that is the problem. In contrast, if I apply this algorithm to simulated images then there is no non-linearity. I have attached simulated images here. Even on experimental images attached in the previous comment, I have applied this algorithm twice and even thrice, but got the same result, no change.

![Picture1](https://user-images.githubusercontent.com/64607461/128448054-5e6f673f-4bec-4f55-a71d-89ae321d8408.jpg)

**Comment by cweickhmann** [comment]
Ah, okay. Thanks for that clarification (I suspected the right-hand plots to be error output w.r.t. to input).

**Comment by mfkasim1** [comment]
> 
> 
> Hi, I tried this algorithm but it worked well with simulation but when I tried real images then results were not satisfactory, still there were some parts that did not unwrapped. Moreover, **performance gets worst with noisy images**. Any idea? what could be the problem?

Hi @Leostar2054, thanks for raising the issue.
It seems like in your image there are "leaks" in the boundary (see red circles in the images below).

<img width="490" alt="Untitled" src="https://user-images.githubusercontent.com/1624640/128533676-1b46386c-28ff-46a7-8825-662910f29fcf.png">

The boundaries with "leaks" are not corrected by the algorithm because the algorithm thinks the regions belong to the same group of phase shift.
I'm not sure the fix for this, but you could try different algorithms, or try the phase unwrap from scikit-image (it has a better implementation).

**Comment by Leostar2054** [comment]
> > Hi, I tried this algorithm but it worked well with simulation but when I tried real images then results were not satisfactory, still there were some parts that did not unwrapped. Moreover, **performance gets worst with noisy images**. Any idea? what could be the problem?
> 
> Hi @Leostar2054, thanks for raising the issue.
> It seems like in your image there are "leaks" in the boundary (see red circles in the images below).
> 
> <img alt="Untitled" width="490" src="https://user-images.githubusercontent.com/1624640/128533676-1b46386c-28ff-46a7-8825-662910f29fcf.png">
> 
> The boundaries with "leaks" are not corrected by the algorithm because the algorithm thinks the regions belong to the same group of phase shift.
> I'm not sure the fix for this, but you could try different algorithms, or try the phase unwrap from scikit-image (it has a better implementation).

Hi @mfkasim1 , Thanks for your suggestion, I tried scikit-image version and it worked better. Results are attached
![22](https://user-images.githubusercontent.com/64607461/129903691-7aed021e-88ec-4af6-a79a-b588e0927a8e.png)
![11](https://user-images.githubusercontent.com/64607461/129903695-36756d20-2da8-4abc-b450-6bc7ccb65496.png)

**Comment by mfkasim1** [comment]
Closed because it is solved by scikit-learn (to be honest, this was the reason I moved from MATLAB to Python a few years ago)
